services:
  angular:
    build:
      context: ./frontend
      args:
        - API_URL=/api
    ports:
      - "4000:4000"
    depends_on:
      - express

  express:
    build:
      context: ./api
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - SECRET=catmon-secret-key
      - NODE_ENV=development
      - MONGO_DB_USERNAME=dbuser
      - MONGO_DB_PASSWORD=password123
      - MONGO_DB_HOST=database
      - MONGO_DB_PORT=27017
      - MONGO_DB_DATABASE=catmon_db
      - MONGO_DB_PARAMETERS=?authSource=admin
    links:
      - database
    depends_on:
      - database

  database:
    image: mongo:latest
    ports:
      - "27018:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=dbuser
      - MONGO_INITDB_ROOT_PASSWORD=password123
      - MONGO_INITDB_DATABASE=catmon_db
    volumes:
      - ./mongo/init-db.d/:/docker-entrypoint-initdb.d/
      - ./mongo/db:/data/db
